### ISSUE TITLE
[BUG] Component's locked and unlocked behavior

### ISSUE THREAD

**Issue by Evgenios95** [react-bratus/react-bratus#29]
**Describe the bug**
Whenever we lock the parent component and we try to move it around with the children, then it works properly. But as soon as we unlock it again through the unlock button, it remains locked. 

**To Reproduce**
1. Go to the localhost
2. Select a component of your choice that has children elements
3. Press the lock icon to move it around with its descendants
4. Press the unlock icon to stop the 'locked' behavior
5. Observe the above-mentioned error

**Expected behavior**
Stop the 'locked' behavior

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Last updated versions

**Comment by stephanboersma** [comment]
@Evgenios95, Good find. I think this can be solved relatively easy in the `src/styles/atoms/ComponentNode/index.js`. Add a new line after line 63 including `setSelectedElements([])`.

**Comment by Evgenios95** [comment]
This is closed due to the removal of the "lock" functionality
