### ISSUE TITLE
Access to react-bratus organization in npmjs

### ISSUE THREAD

**Issue by stephanboersma** [react-bratus/react-bratus#34]
Hi team,

If you want to push updates to the npm package, you should have access to the react-bratus organization on [npmjs](https://www.npmjs.com/org/react-bratus/).

If you provide me with the e-mails of those who need access, then I can add you :-)

Best,
Stephan

**Comment by Evgenios95** [comment]
Great @stephanboersma.
evgeniospam@gmail.com

**Comment by stephanboersma** [comment]
I have invited you, @Evgenios95
