### ISSUE TITLE
[BUG] Simple <> notation doesn't end up as a visible component

### ISSUE THREAD

**Issue by thepiotrek** [react-bratus/react-bratus#38]
**Describe the bug**

In the simplest component where we use the shortcut notation (<>) for <React.Fragment>
react-bratus doesn't take that component into consideration.

**To Reproduce**

Create a component which returns this code.

`return (<> This component text </>)`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser: Safari 
 - Version 14.1.12

**Comment by Evgenios95** [comment]
Team decision: Not important, since noone would create a single string as a component wrapped between <></> in a real-world scenario.
