### ISSUE TITLE
Component Tree Horizontal View

### ISSUE THREAD

**Issue by Evgenios95** [react-bratus/react-bratus#44]
We need to give scalability options to the user.

Our goal is to make the tree scale horizontally, but also make sure that the way it scales, the distance between the nodes, between the ancestors and the children, etc., are done in a nice way.

The user can have the option to interact with our interface with a button and automatically change the way the tree is visualised. We can have a first draft and keep working on it till we think it's good enough.

**Comment by thepiotrek** [comment]
Fixed through pull request #55
