### ISSUE TITLE
Scroll to Zoom

### ISSUE THREAD

**Issue by mircealungu** [react-bratus/react-bratus#79]
Folks, most of the people who didn't grow under a stone, are used to scrolling being mapped on zoom-in/out. In Bratus, currently scrolling moves the canvas. Would it be be complicated to implement scroll-to-zoom? in case it's easy, we should do it.

**Comment by Evgenios95** [comment]
@mircealungu Sure, it's our bad, I think we haven't tested it with a mouse, but only with a trackpad.
The 2-finger is understood as scroll by the trackpad and it's rly convenient to use it to move the canvas.
I will see if there's a way to zoom with scroll on a mouse and move the canvas on a trackpad?
