### ISSUE TITLE
Implementing component details modal.

### ISSUE THREAD

**Issue by Evgenios95** [react-bratus/react-bratus#81]
When you click a node, a modal pops up. The modal should be from Ant-Design, and can be found under https://ant.design/components/modal/. We discussed with @thepiotrek that it would be nice to use the already implemented draggable one from the library, so that the user can drag it around and have a clear view of the tree at all times. Check the examples provided, they have what we need.

<img width="566" alt="Screenshot 2022-04-26 at 17 03 56" src="https://user-images.githubusercontent.com/58588711/165324061-52afe8a6-4062-4d2e-8458-f710e0f903ba.png">

**Thus, the modal is open and:**
1. It has the component name as a title next to the X close button.
2. The background behind the modal is not dark/ blurry, so that the user can have the tree available on his/ her screen.
3. Under the title, it has a small section about the frequency.
4. Under it it should have 2 buttons with a clear text:
      - 1: Open file on VSCode,
      - 2: Display Code Panel. As soon as you click this one, the modal with the code that we already have pops up.

**Why do we need this implementation?** 

As @mircealungu said, it doesn't make sense to display a big modal whenever we click on a component that removes the tree completely from our view. In this case, we have a small modal that can be dragged around by the user, who can also click on a button to see the big panel on demand.

**Comment by Evgenios95** [comment]
@mircealungu  It makes sense, what about a normal popover like the one under: https://ant.design/components/popover/?
You can have it open but still interact with the tree.

Otherwise we could also have a card on the right side of the screen, like the navigation panel, but it's too extra space for such a little info (Frequency + 2 buttons).

So, what about the popover?

**Comment by mircealungu** [comment]
popover is much better than a modal!
