### ISSUE TITLE
More tree filtering options

### ISSUE THREAD

**Issue by Evgenios95** [react-bratus/react-bratus#83]
In today's meeting, we discussed about having some more filtering options:

- Filtering the tree by how many times a component is used.
- Filtering the tree to exclude specific components that the user selects.

Both will happen through inputs in our Navigation Panel.

- [ ]  Times used
- [ ]  Component Names

This will give the option to the user to reduce the noise and exclude components that he/ she doesn't wanna visualise.

**Comment by darde** [comment]
Good call! I also would like to exclude some `__tests__` folder from the tree.

**Comment by Evgenios95** [comment]
> Good call! I also would like to exclude some `__tests__` folder from the tree.

@darde Hi Darde! Could you provide us a screenshot of how the tree looks like after rendering the tests folder and if it's possible (in case it's public) a link to your GitHub project? 😇
